export const HomesArray =[
    {
        id:0,
        image1:"https://media-cdn.tripadvisor.com/media/photo-m/1280/16/10/b3/49/cardamom-grove-homestay.jpg",
        title:"Fagu, Himachal Pradesh",
        stay_name:"Ocean pearl",
        distance:"283 kilometres away",
        price:"₹4,622 night",
        property_spec:"farms",
        date:"9-14 May",
        place_type:"entire place",
        liked:false,
        bedrooms:"3",
        guests_allowed:"4",
        review:"4.43 (23 reviews)",
        beds:"3",
        bathroom:"3",
        specs:["wifi","kitchen","AC","free cancellation","washing machine","iron","free parking","pool","dryer","gym"],
    },

    {
        id:1,
        image1:"https://irisholidays.com/keralatourism/wp-content/uploads/2019/09/harivihar-kerala-homestay.jpg",
        title:"Munnar, Kerala",
        stay_name:"Villa La Isa",
        distance:"2,050 kilometres away",
        price:"₹9,122 night",
        property_spec:"tiny homes",
        date:"8-15 May",
        place_type:"entire place",
        liked:false,
        bedrooms:"2",
        guests_allowed:"3",
        review:"4.23 (54 reviews)",
        beds:"2",
        bathroom:"2",
        specs:["wifi","kitchen","free cancellation","iron","free parking"],
    },

    {
        id:2,
        image1:"https://media-cdn.tripadvisor.com/media/photo-s/1c/77/ab/cf/magod-homestay.jpg",
        title:"New Delhi, Delhi",
        stay_name:"Seas day",
        distance:"850 kilometres away",
        price:"₹2,182 night",
        property_spec:"offbeat",
        date:"5-8 May",
        place_type:"private room",
        liked:false,
        bedrooms:"1",
        guests_allowed:"2",
        review:"3.12 (26 reviews)",
        beds:"2",
        bathroom:"1",
        specs:["wifi","free cancellation","iron","free parking","AC","dryer","washing machine"],
    },

    {
        id:3,
        image1:"https://img.etimg.com/thumb/msid-86088577,width-650,imgsize-408128,,resizemode-4,quality-100/23aac4b2-a36a-4a46-b0a2-942.jpg",
        title:"Pihu, Nepal",
        stay_name:"pearl stay",
        distance:"4,245 kilometres away",
        price:"₹3,467 night",
        property_spec:"Treehouses",
        date:"10-14 May",
        place_type:"private room",
        liked:false,
        bedrooms:"1",
        guests_allowed:"1",
        review:"4.66 (42 reviews)",
        beds:"1",
        bathroom:"1",
        specs:["free cancellation","dryer"],
    },

    {
        id:4,
        image1:"https://3hnp1e3jo9enghwphgtzsuhy-wpengine.netdna-ssl.com/wp-content/uploads/2019/11/Deep-Valley-Homestay.jpg",
        title:"Jibhi- Himachal Pradesh",
        stay_name:"oyo homestay",
        distance:"583 kilometres away",
        price:"₹3,232 night",
        property_spec:"Aframes",
        date:"12-16 May",
        place_type:"shared room",
        liked:false,
        bedrooms:"2",
        guests_allowed:"3",
        review:"2.43 (13 reviews)",
        beds:"3",
        bathroom:"2",
        specs:["wifi","kitchen","AC","free cancellation","washing machine","iron","free parking"],
    },

    {
        id:5,
        image1:"https://pix10.agoda.net/hotelImages/11071126/0/5162164730ff8bc94d1d3063c73d944a.jpg",
        title:"Thrissur, Kerala",
        stay_name:"Sea Germ",
        distance:"173 kilometres away",
        price:"₹3,152 night",
        property_spec:"domes",
        date:"6-8 May",
        place_type:"entire place",
        liked:false,
        bedrooms:"3",
        guests_allowed:"4",
        review:"3.78 (52 reviews)",
        beds:"4",
        bathroom:"3",
        specs:["wifi","kitchen","AC","free cancellation","washing machine","iron","free parking"],
    },

    {
        id:6,
        image1:"https://pix10.agoda.net/hotelImages/247/247676/247676_15060410340028435468.jpg",
        title:"Sigiriya, Central Province",
        stay_name:"Home Plaza",
        distance:"5,673 kilometres away",
        price:"₹2,145 night",
        property_spec:"cabins",
        date:"1-14 May",
        place_type:"private room",
        liked:false,
        bedrooms:"4",
        guests_allowed:"6",
        review:"4.43 (23 reviews)",
        beds:"6",
        bathroom:"4",
        specs:["wifi","kitchen","AC","free cancellation","washing machine","iron","free parking"],
    },


    {
        id:7,
        image1:"https://media-cdn.tripadvisor.com/media/vr-splice-j/02/a7/a6/38.jpg",
        title:"Kalpetta, Kerala",
        stay_name:"Deja blue stay",
        distance:"687 kilometres away",
        price:"₹1,362 night",
        property_spec:"beach front",
        date:"9-14 May",
        place_type:"shared room",
        liked:false,
        bedrooms:"3",
        guests_allowed:"2",
        review:"3.12 (22 reviews)",
        beds:"3",
        bathroom:"4",
        specs:["wifi","kitchen","AC","free cancellation","washing machine","iron","pool"],
    },

    {
        id:8,
        image1:"https://www.visittobengal.com/blog/wp-content/uploads/asas.jpg",
        title:"Kallarkutty, Kerala",
        stay_name:"Costa Del Rey",
        distance:"836 kilometres away",
        price:"₹3,287 night",
        property_spec:"amazing pools",
        date:"18-22 May",
        place_type:"entire place",
        liked:false,
        bedrooms:"4",
        guests_allowed:"6",
        review:"4.67 (122 reviews)",
        beds:"6",
        bathroom:"3",
        specs:["wifi","kitchen","AC","free cancellation","washing machine","iron","free parking","pool","dryer"]
    },

    {
        id:9,
        image1:"https://irisholidays.com/keralatourism/wp-content/uploads/2019/09/eden-garden-heritage-homestay-fort-kochi.jpg",
        title:"Kochi, Kerala",
        stay_name:"Casa Palmera",
        distance:"385 kilometres away",
        price:"₹1,624 night",
        property_spec:"cabins",
        date:"3-12 May",
        place_type:"private room",
        liked:false,
        bedrooms:"1",
        guests_allowed:"2",
        review:"3.12 (78 reviews)",
        beds:"2",
        bathroom:"1",
        specs:["wifi","iron"],
    },

    {
        id:10,
        image1:"https://www.euttaranchal.com/hotels/photos/sundar-homestay-5173221.jpg",
        title:"Manjumala, Kerala",
        stay_name:"Ruby arena",
        distance:"1,345 kilometres away",
        price:"₹2,762 night",
        property_spec:"amazing pools",
        date:"18-24 May",
        place_type:"private room",
        liked:false,
        bedrooms:"2",
        guests_allowed:"2",
        review:"4.22 (67 reviews)",
        beds:"2",
        bathroom:"2",
        specs:["wifi","kitchen","AC","free cancellation","washing machine","iron","free parking","pool","dryer"],
    },

    {
        id:11,
        image1:"https://img.etimg.com/thumb/width-1200,height-900,imgsize-1353365,resizemode-1,msid-76084906/industry/services/travel/homestays-operators-look-for-succour-as-people-stay-home.jpg",
        title:"Jodhpur, Rajasthan",
        stay_name:"Drift wood cottage",
        distance:"3,283 kilometres away",
        price:"₹3,873 night",
        property_spec:"beachfront",
        date:"19-26 May",
        place_type:"private room",
        liked:false,
        bedrooms:"2",
        guests_allowed:"3",
        review:"4.43 (23 reviews)",
        beds:"3",
        bathroom:"2",
        specs:["wifi","kitchen","AC","free cancellation","washing machine","iron","free parking","pool"],
    },
]